apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: autoretrieve
resources:
- ../../base
- monitor.yaml
- pvc.yaml
patchesStrategicMerge:
- service-patch.yaml
- deployment-patch.yaml
replicas:
- name: autoretrieve
  count: 1
secretGenerator:
- name: autoretrieve-identity
  behavior: replace
  files:
  - peerkey.encrypted
images:
- name: autoretrieve
  newName: 407967248065.dkr.ecr.us-east-2.amazonaws.com/autoretrieve/autoretrieve # {"$imagepolicy": "autoretrieve:autoretrieve:name"}
  newTag: 20220527164729-30baa6db9de15a631dcd793ff79242a80378283f # {"$imagepolicy": "autoretrieve:autoretrieve:tag"}
