apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoretrieve
  namespace: autoretrieve
spec:
  template:
    spec:
      # Deploy autoretrieve nodes explicitly on a node group of type r5a.2xlarge in us-east-2a.
      # Because, it uses a PVC volume that is currently created in us-east-2a.
      # This combined with the configured resource limit  makes sure that the worker nodes would 
      # exclusively run autoretrieve pods, avoid scheduling interference cause by the k8s cluster
      # autoscaling/binpacking policy to reduce cost when possible.
      # See: https://github.com/filecoin-project/storetheindex/blob/e5a2bbec268abed470d6211185d074fea4057c2a/deploy/infrastructure/dev/us-east-2/eks.tf#L37
      nodeSelector:
        node.kubernetes.io/instance-type: r5a.2xlarge
        topology.kubernetes.io/zone: us-east-2a
      containers:
        - name: autoretrieve
          volumeMounts:
            - name: cache
              mountPath: /data
          resources:
            limits:
              memory: 60Gi
            requests:
              memory: 60Gi
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: autoretrieve-cache-0
