apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: autoretrieve
resources:
- ../../base
- monitor.yaml
- pvc.yaml
patchesStrategicMerge:
- service-patch.yaml
- deployment-patch.yaml
replicas:
- name: autoretrieve
  count: 1
configMapGenerator:
- name: autoretrieve-config
  behavior: replace
  files:
  - config.yaml
secretGenerator:
- name: autoretrieve-identity
  behavior: replace
  files:
  - peerkey.encrypted
- name: autoretrieve-authorization
  behavior: replace
  files:
  - eventrecorderauth.encrypted
images:
- name: autoretrieve
  newName: 407967248065.dkr.ecr.us-east-2.amazonaws.com/autoretrieve/autoretrieve # {"$imagepolicy": "autoretrieve:autoretrieve:name"}
  newTag: 20221019060205-2171a13846e5d4dbf5bae702e01710b3cc39491c # {"$imagepolicy": "autoretrieve:autoretrieve:tag"}
