apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tornado
resources:
- lassie-event-recorder
images:
- name: lassie-event-recorder
  newName: ghcr.io/filecoin-project/lassie-event-recorder # {"$imagepolicy": "tornado:lassie-event-recorder:name"}
  newTag: 20230801-015923-d246c9f # {"$imagepolicy": "tornado:lassie-event-recorder:tag"}
