apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: autoretrieve
resources:
- ../../base
- monitor.yaml
- pvc.yaml
patchesStrategicMerge:
- service-patch.yaml
- deployment-patch.yaml
replicas:
- name: autoretrieve
  count: 1
secretGenerator:
- name: autoretrieve-identity
  behavior: replace
  files:
  - peerkey.encrypted
images:
- name: autoretrieve
  newName: 407967248065.dkr.ecr.us-east-2.amazonaws.com/autoretrieve/autoretrieve # {"$imagepolicy": "autoretrieve:autoretrieve:name"}
  newTag: 20220728143244-01a3307cdc698d6b881e11ab086339e20a873395 # {"$imagepolicy": "autoretrieve:autoretrieve:tag"}
