apiVersion: v1
stringData:
    mongoaddr: ENC[AES256_GCM,data:pJsFHu1k7f0TLJSbobYDsqEZqy7S691HFqwt+1WX8gD1gzYdU8XP+c0S4VOqbpSfakdyruDUqzpXrVLFBAUl/YhlXgyUR/PYlYN8YOZllhwneOM8dnn2prxNoYZ7YYCbkzDeZSjj01kBM7gX,iv:vWCbBps26Ao8Y5vbB4ss+d14Dy+QaXH0I71h27EoZRw=,tag:Xwjo/ugVr5mcPBRXV7N35w==,type:str]
kind: Secret
metadata:
    labels:
        app: lassie-event-recorder
    name: lassie-event-recorder-mongo-creds
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:407967248065:alias/dev/us-east-2/autoretrieve
          created_at: "2023-05-15T22:08:45Z"
          enc: AQICAHgZ4zxFMLYL2iEHWJJh7edGwSAfx3nqUsNmImHieESc3QF5OOx1+/u9ZX3Q+fyxIIoBAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3fYWP0YFYuHFlO2YAgEQgDvYsitcfF5goWIAkNcyKdN9HfFw1g9E0UKkRkriaWl9g4iY8uUU+iFHZQCrugTqMwViA8Xp4psDfeKdPg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-15T22:08:45Z"
    mac: ENC[AES256_GCM,data:+SHAg/2T59xRQ5rEKcHLciasXhnf1Mqig9r+WAZVwMeNTtCFUT2FDUnanYcvMy+GJebQ4GtaQtNW3JDQZimn8uSO0C+MC+rEFAX4t7ylJY6ohgMxTb1fuLdVGVwjJuQMkkEjaykVg/KFH9LylPJXF+0sdeFWHwrD8ZPFrMx0p+Q=,iv:6ajpFojLmrGFp8Iu9rRXUHYEhxWO5jFnqfENXyg8La0=,tag:gl/M7jXKWcd8RhujZM035g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
